language: node_js
sudo: false
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
node_js: stable
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
  sauce_connect: true
